# Generated by Django 6.0 on 2026-01-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_stop_routestop_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='latitude',
            field=models.FloatField(default=23.8103),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='longitude',
            field=models.FloatField(default=23.8103),
            preserve_default=False,
        ),
    ]
