# Generated by Django 5.2.8 on 2026-01-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_stop_latitude_stop_longitude'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fare',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fare',
            name='from_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_stop', to='transport.stop'),
        ),
        migrations.AlterField(
            model_name='fare',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route'),
        ),
        migrations.AlterField(
            model_name='fare',
            name='to_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_stop', to='transport.stop'),
        ),
    ]
